import Foundation
import Clibgit2

public let libGit2ErrorDomain = "org.libgit2.libgit2"

internal extension NSError {
	/// Returns an NSError with an error domain and message for libgit2 errors.
	///
	/// :param: errorCode An error code returned by a libgit2 function.
	/// :param: libGit2PointOfFailure The name of the libgit2 function that produced the
	///         error code.
	/// :returns: An NSError with a libgit2 error domain, code, and message.
	convenience init(gitError errorCode: Int32, pointOfFailure: String? = nil) {
		let code = Int(errorCode)
		var userInfo: [String: String] = [:]

		if let message = errorMessage() {
			userInfo[NSLocalizedDescriptionKey] = message
		} else {
			userInfo[NSLocalizedDescriptionKey] = "Unknown libgit2 error. (code \(errorCode))"
		}

		if let pointOfFailure = pointOfFailure {
			userInfo[NSLocalizedFailureReasonErrorKey] = "\(pointOfFailure) failed."
		}

		self.init(domain: libGit2ErrorDomain, code: code, userInfo: userInfo)
	}
}

/// Returns the last error message generated by libgit2 in the current thread, if any.
///
/// `giterr_last()` is thread-local — always build the `NSError` on the same thread that made
/// the failing libgit2 call.
///
/// (An earlier version took the error code and fell back to `strerror(errno)` when
/// `UInt32(errorCode) == GIT_ERROR_OS.rawValue`. That comparison confused libgit2 *return
/// codes* — always negative — with the `git_error_t` error-*class* constants, so it could
/// never be true; worse, `UInt32(negativeCode)` traps, turning the error-reporting path itself
/// into a crash whenever no thread-local error was recorded. Fixed for anglesite/SwiftGit2
/// (Anglesite-app#653).)
private func errorMessage() -> String? {
	guard let last = giterr_last() else { return nil }
	return String(validatingUTF8: last.pointee.message)
}

public extension NSError {
	/// The raw libgit2 error code (`git_error_code`) when this error came from SwiftGit2's
	/// libgit2 error domain, or nil otherwise. Prefer these typed checks over string-matching
	/// `localizedDescription`, whose wording libgit2 doesn't guarantee. Added for
	/// anglesite/SwiftGit2 (Anglesite-app#653).
	var libGit2ErrorCode: Int32? {
		return domain == libGit2ErrorDomain ? Int32(exactly: code) : nil
	}

	/// True for libgit2's "not found" (`GIT_ENOTFOUND`) — a missing reference, remote, config
	/// entry, or repository.
	var isLibGit2NotFound: Bool {
		return libGit2ErrorCode == GIT_ENOTFOUND.rawValue
	}

	/// True when the remote rejected the supplied credentials: either libgit2's own
	/// `GIT_EAUTH`, or SwiftGit2's bounded credential retry giving up (also reported as
	/// `GIT_EAUTH` — see `RemoteCallbackPayload.makeAuthenticationError()`).
	var isLibGit2AuthenticationFailure: Bool {
		return libGit2ErrorCode == GIT_EAUTH.rawValue
	}
}
